services:
  api:
    container_name: production_api
    build:
      context: ./
      dockerfile: src/Bmb.Production.Api/Dockerfile
      tags:
        - techchallenge/restaurant_api
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - tech-challenge
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
      - Serilog__Enrich__0=FromLogContext
      - JwtOptions__SigningKey=${JwtOptions_SigningKey}
      - JwtOptions__Issuer=${JwtOptions_Issuer}
      - JwtOptions__Audience=${JwtOptions_Audience}
      - JwtOptions__ExpirationSeconds=${JwtOptions_ExpirationSeconds}
      - JwtOptions__UseAccessToken=${JwtOptions_UseAccessToken}
      - RedisSettings__Host=redis
      - RedisSettings__Port=6379

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - tech-challenge

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - tech-challenge


networks:
  tech-challenge:
    driver: bridge
